proxmox_cluster: pve

proxmox_root: "root@pam"
## Read the root password from the vault and copy here at runtime:
proxmox_root_password: "{{ vault_proxmox_root_password }}"

proxmox_master_ip: 192.168.0.11

proxmox_kvm_admin: "root@pam"
## Read the root password from the vault and copy here at runtime:
proxmox_kvm_admin_password: "{{ vault_proxmox_root_password }}"

### Proxmox KVM templates for Ubuntu 18.04 LTS (bionic):
### (names are loosly based off AWS instance sizes)
### Instance Name                RAM   vCPU  Template ID
###  ubuntu-bionic.m1-nano       0.5     1     9000
###  ubuntu-bionic.m1-micro      1       1     9001
###  ubuntu-bionic.m1-small      2       2     9002
###  ubuntu-bionic.m1-medium     4       2     9003
###  ubuntu-bionic.m1-large      8       2     9004
###  ubuntu-bionic.m1-xlarge     16      4     9005
###  ubuntu-bionic.c1-small      2       4     9101
###  ubuntu-bionic.c1-medium     4       4     9102
###  ubuntu-bionic.c1-large      8       4     9103
###  ubuntu-bionic.c1-xlarge     16      6     9104

ubuntu_bionic_cloud_image_url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
ubuntu_bionic_cloud_image: /mnt/pve/cephfs/template/iso/bionic-server-cloudimg-amd64.img
ubuntu_bionic_m1_nano_template_id: 9000
ubuntu_bionic_m1_micro_template_id: 9000
ubuntu_bionic_m1_small_template_id: 9000
ubuntu_bionic_m1_medium_template_id: 9000
ubuntu_bionic_m1_large_template_id: 9000
ubuntu_bionic_m1_xlarge_template_id: 9000
ubuntu_bionic_c1_small_template_id: 9000
ubuntu_bionic_c1_medium_template_id: 9000
ubuntu_bionic_c1_large_template_id: 9000
ubuntu_bionic_c1_xlarge_template_id: 9000
